sudo: required

services:
    - docker

before_install:
    - docker build -t yar0/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run yar0/react-test npm test -- --coverage


after_success:
    - docker build -t yar0/multi-client ./client
    - docker build -t yar0/multi-nginx ./nginx
    - docker build -t yar0/multi-server ./server
    - docker build -t yar0/multi-worker ./worker
# Login to the docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# TAKE IMAGES AND PUSH TO docker hub
    - docker push yar0/multi-client
    - docker push yar0/multi-server
    - docker push yar0/multi-nginx
    - docker push yar0/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-740594152866
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY

